### ISSUE TITLE
Undefined index for backgroundColor

### ISSUE THREAD

**Issue by dovy** [godaddy-wordpress/coblocks#1531] opened 2020-06-11 12:29 UTC
### Describe the bug:
`PHP Notice: Undefined index: backgroundColor in ~/plugins/coblocks/src/blocks/share/index.php on line 108`

### To reproduce:
Not sure, showed up in my logs.

### Expected behavior:
Add an isset in there.  ;)

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [x ] This bug happens **without** the Gutenberg plugin active
- [ ] I can reproduce this bug consistently using the steps above

### WordPress version:
5.4.2

### Gutenberg version:
Default

**Comment by jrtashjian** [comment] 2020-07-13 22:52
This will get resolved for the next release if it hasn't been already.

**Comment by jrtashjian** [comment] 2020-07-16 21:19
I've tested a bunch of combinations and cannot reproduce the error. We do have checks for each attribute key before we use them. Closing.

**Closed by jrtashjian** 2020-07-16 21:19 UTC
Labels: [Priority] Low, [Type] Bug
