### ISSUE TITLE
Masonry gallery shows blended images

### ISSUE THREAD

**Issue by rickmgithub** [godaddy-wordpress/coblocks#1658] opened 2020-09-02 14:38 UTC
### Describe the bug:
When a Masonry gallery is used on the Soho theme but images start to overlay on top of each other.

WHAT I FOUND:
* It looks good in the editor - https://d.pr/i/bDcON6
* But on desktop shows this - https://d.pr/i/kT3f7Z
* On mobile this - https://d.pr/i/AVgV5t
* Turned off other plugins. No change
- Ultimate Addons for Gutenberg
- Visual Portfolio
* Created a test page on a separate site which did the same.
* In fact when you first view the page it looks ok on desktop sometimes but when you switch to mobile view it messes up - https://d.pr/v/68qJor
* Same on 2020 theme

### Expected behavior:
Layout to look like editor view

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

#3280800-zd

**Comment by kristarella** [comment] 2020-09-14 05:51
Overlapping issue also occurs in Janice theme
3313816-zd

**Comment by hacchism** [comment] 2020-10-04 06:13
Another report(with Janice theme): #24601212-hc

**Comment by eduardozulian** [comment] 2020-11-05 16:35
Looks like this was fixed in #1370 but I am still seeing issues on another WordPress.com site.

**Comment by marktmcgrath** [comment] 2020-11-17 16:48
Might be worth exploring if there's a conflict with Jetpack's lazy loading of images. We were experiencing a similar issue on [this site](https://irinalazar258785262.wpcomstaging.com/projects/nova-interior-styling-design/) and when we disabled Lazy Loading, the overlapping image issues _appears_ to be fixed on mobile.

**Comment by liviopv** [comment] 2021-02-02 19:39
I was able to reproduce it with [Mayland](https://wordpress.com/theme/mayland), which makes me think this could be affected all Varia child themes too.

@marktmcgrath I was able to reproduce with and without lazy load and photon, so I don't think it's related.

Screenshot of this page https://atlivio.wpcomstaging.com/masonry-gallery-test/ on mobile:

![Screenshot](https://d.pr/i/cdxnDN+)
Screenshot: https://d.pr/i/cdxnDN

**Comment by liviopv** [comment] 2021-02-03 08:59
Twenty Sixteen theme on a free WordPress.com site when viewed on Chrome 78/Mac Os Bis Sur:

![Screenshot](https://d.pr/i/mO8aA9+)
Screenshot: https://d.pr/i/mO8aA9

Cubic theme on a free WordPress.com site when viewed on Chrome 78/Mac Os Bis Sur:

![Screenshot](https://d.pr/i/nnYmpO+)
Screenshot: https://d.pr/i/nnYmpO

**Comment by JoshuaGoode** [comment] 2021-02-03 19:25
So far we can now reproduce on WordPress.com sites, WordPress.com Business plan sites with the repo version of the plugin installed, and self-hosted sites.  All using WPCOM provided themes and also third-party themes from the .org repo.

The easiest steps to reproduce are the following:

1. Add a Masonry gallery to a page or post.
2. View the page or post on a mobile browser or via browser dev tools set to mobile screen dimensions.

Just ran a quick test on a self-hosted site with just and CoBlocks installed and Twentytwenty.  Issue appeared in multiple browsers.

Sorry for another direct ping @AnthonyLedesma , looks like this has escalated sometime recently and is more widespread than we initially thought.

**Comment by joweber123** [comment] 2021-02-15 02:35
Another report here with Storefront- 3738332-zen

**Comment by sourourn** [comment] 2021-02-28 14:55
Reported once again with the Mayland theme, site is on a Personal plan. Screenshot: https://d.pr/i/NYqBQq
The issue is happening intermittently on both desktop and mobile. 

Devices:
iPhone 12 mini, iOs 14.4, and with Safari.
Windows 10 latest update, using Microsoft Edge.

**Comment by benchilcote** [comment] 2021-03-05 20:52
Another report.  Masonry Gallery overlapping on mobile.  Screenshot from my troubleshooting in Browserstack:  https://d.pr/i/i7CAQj   Theme: Coutoire.  I was not able to reproduce on a test website.  

21596946-hc / 3796368-zen

Device:  iPhone 12 mini

**Comment by jrtashjian** [comment] 2021-03-24 20:42
Hey all, I've just looked into this issue and was abkle to reproduce although unable to resolve. It seems the issue is coming from the jQuery Masonry library included with WordPress Core. Here's is an issue from the project's repository that identifies the same issue: https://github.com/desandro/masonry/issues/1147

I'm going to close this because it's out of our control here.

**Closed by jrtashjian** 2021-03-24 20:42 UTC
Labels: [Priority] Low, [Type] Bug
