### ISSUE TITLE
Gallery block Lightbox doesn't work past the first 3-4 images.

### ISSUE THREAD

**Issue by jwold** [godaddy-wordpress/coblocks#1887] opened 2021-04-19 05:15 UTC
### Describe the bug:

I'm using the gallery block with the Lightbox feature turned on. It seems to be functioning fine in Local by Flywheel, but up on the production server I'm seeing an issue where it's not loading properly; so I don't know if this is a hosting issue or a CoBlocks gallery issue. 

Here's a video of the issue happening: https://v.usetapes.com/8ULBpjUBV3
This is the page in question: https://www.enduringdesignstudio.com/bonners-ferry/

Would love any help, thanks so much!

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [ ] This bug happens **without** the Gutenberg plugin active
- [ ] I can reproduce this bug consistently using the steps above

**Comment by olafleur** [comment] 2021-07-06 20:41
When going to the page in question, in Firefox, Chrome and Safari, I am unable to reproduce the problem that you had in the video. Did you do a fix on your website?

**Comment by snovosel-godaddy** [comment] 2021-07-13 19:54
I am also unable to reproduce this problem following the above steps as well as on new pages . It is possible that this is a bug with the image on the hosting provider. I will close this ticket for now

**Closed** 2021-07-13 19:55 UTC
Labels: [Priority] Low, [Type] Bug
