### ISSUE TITLE
Hero Block Woocommerce Style seem to conflict

### ISSUE THREAD

**Issue by Vyeche** [godaddy-wordpress/coblocks#1471] opened 2020-04-28 21:56 UTC
The buttons are stacking on top of each other. 

![image](https://user-images.githubusercontent.com/972377/80541623-78dcb600-8979-11ea-92b7-92576d19d42b.png)

**Comment by AnthonyLedesma** [comment] 2020-04-30 13:37
Hi @Vyeche,

I cannot replicate this with TwentyTwenty. What theme are you using in this screenshot?

**Comment by Vyeche** [comment] 2020-04-30 13:55
Hi,

Using the theme called twenty twenty with Woo commerce shop page.

Kind regards,
Vye

**Comment by jrtashjian** [comment] 2020-07-14 01:13
Assigning this to myself as a reminder to attempt to reproduce with new information given.

**Comment by jrtashjian** [comment] 2020-07-16 16:19
I am able to replicate this issue on the front-end. The buttons stack when viewing the page but render properly when viewed in the block editor. The Twenty Twenty and Go themes display the buttons stacked, Twenty Seventeen seems to render them properly.

**Comment by EvanHerman** [comment] 2020-07-16 16:28
I too can replicate this. It seems that if we just throw a max-width on the `.wp-block-coblocks-hero__content .alignleft` and `.wp-block-coblocks-hero__content .alignright` elements, this would resolve itself.

**Comment by EvanHerman** [comment] 2020-07-16 16:38
I'm not entirely sure the best route to fix this. It looks like just increasing the `max-width` property of the hero block, in the editor, will fix it. In my testing I set mine to 1000px (max), which fixed the button stacking issue with no other obvious changes.

![image](https://user-images.githubusercontent.com/5321364/87698137-12d62280-c761-11ea-8c5f-0b718176aa44.png)

**Comment by jrtashjian** [comment] 2020-07-16 20:33
Looks like we have an issue with the width control anyway that will need fixing. This control should probably have been percentage based rather than pixels, maybe we can change it.

![Kapture 2020-07-16 at 16 26 45](https://user-images.githubusercontent.com/375788/87719409-504aa800-c781-11ea-860f-e3c72dddee81.gif)

**Comment by jrtashjian** [comment] 2020-12-16 17:40
This stacking issue is still happening in our Go theme but seems to be resolved in TwentyTwenty and TwentyTwenty-One.
I'm no longer seeing console errors related to the width control.

**Comment by snovosel** [comment] 2021-12-16 11:54
@Vyeche are you still able to reproduce this? With current versions I have not been able to. Are there specific woo-commerce blocks/elements that are causing the styling conflict?

**Comment by Vyeche** [comment] 2021-12-16 12:15
Hi,

I haven't checked in a while. I have moved to use Elegant Themes block
editor.

Kind regards,
Vye

**Comment by snovosel** [comment] 2021-12-16 22:58
I have installed WooCommerce 4.0.1 and tested using newer version of CoBlocks and was not able to reproduce given the provided steps. If this is still an issue please open another issue with updated version numbers / information.

**Closed by snovosel** 2021-12-16 22:58 UTC
Labels: [Type] Bug, Good First Issue, [Priority] Low, [Type] Woo
