### ISSUE TITLE
ISBAT Features block selection collapses on hover

### ISSUE THREAD

**Issue by gdandrija** [godaddy-wordpress/coblocks#1888] opened 2021-04-19 22:31 UTC
### Describe the bug:
When you hover over the Features block in the sidebar, the entire sidebar collapses

### Expected behavior:
This block should show block description and needs to be selected properly regardless of the selection method

### Screenshots:
I have something better, a video link:
https://drive.google.com/file/d/1tn1DWfdmj-uW3Gl3i5v6Z88heUqKwBRI/view

### Isolating the problem:

- [x ] This bug happens with no other plugins activated
- [x ] This bug happens with a default WordPress theme active
- [x ] This bug happens without the Gutenberg plugin active
- [x ] I can reproduce this bug consistently using the steps above

### WordPress version:
5.7.1

Additional notes:
The bug cannot be replicated with the Gutenberg plugin active, still, CoBlocks should work properly without it. In the block search block can still be selected properly, but not in the sidebar.

This issue was initially reported on WordPress.org: https://wordpress.org/support/topic/cannot-select-the-features-block/

**Comment by snovosel-godaddy** [comment] 2021-08-02 18:56
I was not able to reproduce this bug following the above steps. @gdandrija are you able to confirm if this is still an issue?

**Comment by jonathanbardo** [comment] 2021-10-05 14:16
I can't reproduce this either. I'm closing this for now.

**Closed by jonathanbardo** 2021-10-05 14:16 UTC
Labels: [Type] Bug, [Priority] Low
