### ISSUE TITLE
ISBAT use the Lightbox on the aligned Image Block element

### ISSUE THREAD

**Issue by PavleMarjanovic** [godaddy-wordpress/coblocks#1785] opened 2020-12-26 07:46 UTC
### Describe the bug:

I should be able to use the Lightbox on the Image block element that has some type of alignment applied.

### To reproduce:

1. Create an Image block
2. Enable Lightbox feature for this Image Block
3. Add any type of alignment to the Image Block
4. Try to use the Lightbox on the front-end on this Image Block element

### Expected behavior:

The Lightbox should be functional after the alignment.

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

5.6

**Comment by AnthonyLedesma** [comment] 2021-01-04 20:03
This is a duplicate of https://github.com/godaddy-wordpress/coblocks/issues/1782.

**Closed by AnthonyLedesma** 2021-01-04 20:03 UTC
Labels: [Priority] Low, [Type] Bug
