### ISSUE TITLE
ISBAT Add Captions to Carousel Gallery Images

### ISSUE THREAD

**Issue by dotsam** [godaddy-wordpress/coblocks#1578] opened 2020-07-18 21:56 UTC
### Is your feature request related to a problem? Please describe.
I should be able to add captions to individual images in a carousel gallery.

### Describe the solution you'd like
Much as masonry, offset, and stacked gallery formats support captions on individual items, I would like to see the same support in the carousel gallery type.

### Describe alternatives you've considered
No alternatives are possible with the carousel gallery block for individual item captions.

### Additional context/screenshots
I've done a basic port over of the caption functionality from the masonry gallery block to the carousel gallery block, and confirmed the basics are all working. Some consideration will need to be given to how captions appear alongside page dot navigation, and there also seems to be an issue with something swallowing keystrokes/changing focus when typing in the caption field, so you can only type one letter before having to focus the field again.

**Comment by richtabor** [comment] 2020-07-20 14:09
Thanks @dotsam - I'll close this as its a duplicate of #1206, but we'll see what we can do. 👍

**Closed by richtabor** 2020-07-20 14:09 UTC
Labels: [Priority] Low, [Type] Enhancement
