### ISSUE TITLE
ISBAT See Post content in the Post Grid correctly in Google Chrome

### ISSUE THREAD

**Issue by jordesign** [godaddy-wordpress/coblocks#1729] opened 2020-10-11 10:55 UTC
### Describe the bug:
There seem to be some fairly major display issues with the 'Post' block in Chrome. It seems to hide post content behind the featured image - and also has no padding/gutter between columns.

The post content being hidden seems to be limited to Google Chrome - but the lack of padding appears across browsers.

### To reproduce:

1. Ensure your site has at least 1 (but make it a couple) of posts with a featured image assigned.
2. In a new page insert a 'Posts' block which includes the posts with the featured images.
3. Publish page - and view in browser

### Expected behavior:
I expect the site to display consistently across major browsers - and for content in the grid to be visible/readable.

### Screenshots:

<img width="638" alt="Screen Shot 2020-10-11 at 9 53 41 pm" src="https://user-images.githubusercontent.com/1842363/95676744-40b9ee80-0c0c-11eb-8262-2ec1e379c46f.png">
Screenshot in Firefox (displaying as expected)

<img width="633" alt="Screen Shot 2020-10-11 at 9 54 17 pm" src="https://user-images.githubusercontent.com/1842363/95676757-54fdeb80-0c0c-11eb-9192-c152878d1d2a.png">
Screenshot in Chrome (Version 85.0.4183.121)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.5.1

**Comment by jordesign** [comment] 2020-10-11 10:56
Example URL for testing - https://grumpy-rainbow.jurassic.ninja/testing-coblocks-post-grid/

**Comment by jlemay-godaddy** [comment] 2021-10-05 18:06
Closing as I can't reproduce. Layout is looking good.

**Closed by jlemay-godaddy** 2021-10-05 18:06 UTC
Labels: [Type] Bug, [Priority] Low
