### ISSUE TITLE
Social Profiles not displaying correctly

### ISSUE THREAD

**Issue by rickmgithub** [godaddy-wordpress/coblocks#1480] opened 2020-05-03 09:15 UTC
### Describe the bug:
In the editor social profiles look like this - https://d.pr/i/USSZth
On the published page they look like this - https://d.pr/i/MmvgJe

### To reproduce:
Theme: Stratford
Page being worked on is the home page - https://canimakeahitpodcast.com/
Add social profiles and then publish the page
AT site but with no additional plugins

### Expected behavior:
The published page to show the social icons as per the editor page

### Screenshots:
Pls see above

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

**Comment by richtabor** [comment] 2020-05-13 16:16
Hey Rick, appreciate the report. Were you able to uncover what's going on here? Here's what I'm seeing on your site: 
<img width="883" alt="Screen Shot 2020-05-13 at 12 15 02 PM" src="https://user-images.githubusercontent.com/1813435/81837874-63d45b00-9513-11ea-97b4-5ec273fca28e.png">

**Comment by richtabor** [comment] 2020-05-20 17:02
Doesn't look like the issue is currently present anymore, going to close this. 👍

**Closed** 2020-05-26 18:18 UTC
Labels: [Priority] Low, [Status] Needs Info, [Type] Bug
