### ISSUE TITLE
ISBAT open a new or existing page in the editor with coblocks 2.7.0 active

### ISSUE THREAD

**Issue by katiebethbrown** [godaddy-wordpress/coblocks#1815] opened 2021-02-03 00:56 UTC
### Describe the bug:
The block editor will not load in Safari (tested in 14.0.2) with coblocks 2.7.0 active. Instead the message `The editor has encountered an unexpected error.` is displayed, and recovery options are unsuccessful.

This only happens on Safari, and in all my testing it only occurs on pages. Posts appear to load correctly.

There is a console error that appears related as well. 

`TypeError: window.cancelIdleCallback is not a function. (In 'window.cancelIdleCallback(Cc)', 'window.cancelIdleCallback' is undefined) — coblocks.js:57`

<img width="1325" alt="Screen Shot 2021-02-02 at 5 54 29 PM" src="https://user-images.githubusercontent.com/42279181/106682437-bd882400-657f-11eb-9388-5f4f79c46399.png">

### To reproduce:
1. Install and activate coblocks 2.7.0
2. Add a new page, or open an existing one in Safari
3. See error message.

<img width="931" alt="j6Bzf9" src="https://user-images.githubusercontent.com/42279181/106682231-494d8080-657f-11eb-9614-4ee16fa6248d.png">

### Expected behavior:
For the editor to open to a new page or to my current page content

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

5.6

### Gutenberg version:

9.8.3

**Comment by hacchism** [comment] 2021-02-03 01:54
Another report in 27466887-hc

Disabling CoBlocks plugin has worked!

**Comment by pauloeaquino** [comment] 2021-02-03 02:00
27466668-hc

Resolved by deactivating CoBlocks plugin

**Comment by devNigel** [comment] 2021-02-03 02:45
3707559-zd

Disabled CoBlocks plugin.

**Comment by bobmatyas** [comment] 2021-02-03 03:36
27124048-hc 

User left chat before we could narrow it down to CoBlocks/Safari combo, but I reproduced the issue in Safari and resolved it for them by recommending a different browser

**Comment by hacchism** [comment] 2021-02-03 04:09
25851280-hc

Resolved by deactivating CoBlocks plugin.

**Comment by pauloeaquino** [comment] 2021-02-03 05:05
27469799-hc

In this instance, they were getting the error when attempting to copy a page. Resolved by deactivating coblocks plugin.

**Comment by brandonpayton** [comment] 2021-02-03 06:05
The problem appears to be [here](https://github.com/godaddy-wordpress/coblocks/blob/c99cd8c32a91de33148c523a1c0c7c2952f62313/src/extensions/layout-selector/hooks/useComputedLayouts.js#L65) since that is coblocks' only use of the `cancelIdleCallback()`.

According to MDN, the requestIdleCallback method is not supported by Safari:
https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback#browser_compatibility

In case it helps as an example, Gutenberg's priority-queue package uses a `request-idle-callback` module that relies on `requestAnimationFrame()` when `requestIdleCallback()` is not available.

**Comment by JoshuaGoode** [comment] 2021-02-03 14:55
@AnthonyLedesma looks like this is pretty widespread. Seeing reports in your forums as well: https://wordpress.org/support/topic/2-7-update-causes-unrecoverable-error-in-block-editor/

**Closed** 2021-02-03 17:02 UTC
Labels: [Priority] Low, [Type] Bug

**Comment by AnthonyLedesma** [comment] 2021-02-03 17:45
Thank you for the reports, everyone. We are working on getting a hotfix release out for this now.

**Comment by retnonindya** [comment] 2021-02-04 03:16
Hi @AnthonyLedesma 👋  Sorry for the ping. Just to check here, is the fix already deployed? Some folks confirmed that everything looks good, so I presume fix already launched? 😅  Thank you

**Comment by JoshuaGoode** [comment] 2021-02-04 18:49
@

> Hi @AnthonyLedesma 👋 Sorry for the ping. Just to check here, is the fix already deployed? Some folks confirmed that everything looks good, so I presume fix already launched? 😅 Thank you

@retnonindya the fix was merged in https://github.com/godaddy-wordpress/coblocks/pull/1816

Version 2.7.2 dropped yesterday with this: https://wordpress.org/plugins/coblocks/#developers

For us, we'll just need to make sure users have the latest version.

**Comment by retnonindya** [comment] 2021-02-05 02:34
Thank you so much, Joshua! 🙏 And yes, Drue confirmed it yesterday and we have updated the users. Thanks again!
