### ISSUE TITLE
Shape divider block constantly becoming invalid in editor

### ISSUE THREAD

**Issue by DustinWStout** [godaddy-wordpress/coblocks#789] opened 2019-08-27 17:45 UTC
**Describe the bug**
I use the Shape Divider block constantly across my various web properties and nearly every time I go back  in to edit a page that contains a Shape Divider block, it shows the error message, 

> This block contains unexpected or invalid content.

<img width="1166" alt="Screen Shot 2019-08-27 at 10 38 16 AM" src="https://user-images.githubusercontent.com/2152604/63794709-645e9000-c8b7-11e9-81ce-3babcc8d32ce.png">

When I try to resolve the issue with the "Resolve" button, it doesn't actually resolve the way it should. So I have to delete it and create a new Shape Divider.

**To Reproduce**

1. Create a page that contains the Shape Divider block (preferably multiple ones throughout the page)
2. Save/Publish/Update the page
3. Come back the next day

**Screenshots**
Added above

**Expected behavior**
It should just stay a proper Shape Divider block, without errors.

**Isolating the problem:**
Mark completed items with an [x].

-   [ ] This bug happens with no other plugins activated
-   [ ] This bug happens with a default WordPress theme active
-   [ ] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Version**
5.2.2

**Gutenberg Version**
n/a

**Comment by jrtashjian** [comment] 2020-07-23 20:18
Confirming that this is an issue and only occurs for non-admin users. Block validation fails because the SVG markup is not saved to the page.

This is absolutely related to #455 and I feel like this should be a high priority.

**Comment by richtabor** [comment] 2020-07-24 16:00
> Confirming that this is an issue and only occurs for non-admin users. Block validation fails because the SVG markup is not saved to the page.
> 
> This is absolutely related to #455 and I feel like this should be a high priority.

Is this something we can do, or is a core bug?

**Comment by jrtashjian** [comment] 2020-12-15 21:32
Closing this as a duplicate of #455 as we cleanup our issue tracker.

**Closed by jrtashjian** 2020-12-15 21:32 UTC
Labels: [Priority] High, [Type] Bug
