### ISSUE TITLE
Improvements to the Accordion Block

### ISSUE THREAD

**Issue by AlchemyUnited** [godaddy-wordpress/coblocks#886] opened 2019-09-17 19:36 UTC
1) Anchors - Being able to link directly to an accordion item would be helpful. For example, having a list of FAQs and being able to refer (read: share) to the specific one would be a use-case (we wish we could use). 

2) Retitling the main block Accordion Group would also be helpful. As FAQs were being added the person doing the adding was under the impression they were adding a series of single accordions, That is there was no real indication they were being grouped until after the fact. 

2.1) The placeholder of "Add accordion title" should probably be "Add accordion item title." 

3) While there is an icon for Display Open in the toolbar, you can only see that if an item is currently active.  Having some sort of visual indicator (e.g,, different background pattern) that doesn't require a click would be helpful from an editors' approval process POV. 

4) This is a long shot but there might be an argument for being able to use a heading for the title. If nothing else, that would solve the anchor issue.

**Comment by richtabor** [comment] 2019-10-15 14:44
> * Anchors - Being able to link directly to an accordion item would be helpful. For example, having a list of FAQs and being able to refer (read: share) to the specific one would be a use-case (we wish we could use).
> * Retitling the main block Accordion Group would also be helpful. As FAQs were being added the person doing the adding was under the impression they were adding a series of single accordions, That is there was no real indication they were being grouped until after the fact.

This could be resolved by having a Heading block exist above the accordions (which is probably likely). The Heading block can receive anchors and can tie multiple accordion items as a section. 

> * The placeholder of "Add accordion title" should probably be "Add accordion item title."

For 2.1, I agree - good call out.

> While there is an icon for Display Open in the toolbar, you can only see that if an item is currently active. Having some sort of visual indicator (e.g,, different background pattern) that doesn't require a click would be helpful from an editors' approval process POV. 

I do think we need a better way to handle the accordion items here. Perhaps the accordion should close if it's not set to display open - as if it were on the frontend. 

> This is a long shot but there might be an argument for being able to use a heading for the title. If nothing else, that would solve the anchor issue.

Is it proper HTML to include headings in <details>?

**Comment by AlchemyUnited** [comment] 2019-10-15 15:23
"I do think we need a better way to handle the accordion items here. Perhaps the accordion should close if it's not set to display open - as if it were on the frontend."

fwiw, such things are VERY common in GB ATM. That is, the only way to see some of the essentials about a block is to inspect it. That's unnecessary friction. It would be nice is core would address such things. 

Is it proper HTML to include headings in <details>?
Not sure. But the current title is not within <details>, is it?

**Comment by richtabor** [comment] 2020-01-08 22:17
@AlchemyUnited Do you mind shedding some light here and responding to my previous comment on OCT 15th? Just trying to keep this issue from getting too stale. Thanks!

**Comment by AlchemyUnited** [comment] 2020-01-09 00:12
@richtabor - last year? you're expecting me to remember? lol :) but ok, i'll try...

i think the gist of my suggestion is this: often (read: too often) in GB - note: not just your block(s) so don't take this personal :) - a content-creator has to make a block the active block in order to get some detail that's hidden otherwise. 

specifically, for this block, i can't see the current setting for Display Open without the block being active. i'm suggesting an icon and/or background pattern could be used to indicate that value when the block is not the active block. else, for example, someone in the editor / approval role will have to click in only to find out the setting was what they wanted. 

i hope that helps.

**Comment by richtabor** [comment] 2020-01-09 18:19
@AlchemyUnited, I appreciate the insight. Just to confirm, the issue is that you can't tell visually which accordion items are set to display open, and which aren't (unless you click on the accordion item and check the Display Open icon) - correct?

**Comment by AlchemyUnited** [comment] 2020-01-09 18:34
@richtabor - yeah i think that's it. also, it's not unique to the accordion. perhaps for CoBlock but i've seen the pattern with other blocks (i.e., "i wish i could see X or Y without having the click. even a hover would be +).

**Comment by richtabor** [comment] 2020-02-24 19:16
Noting that we've updated the accordion item title placeholder:

<img width="726" alt="Screen Shot 2020-02-24 at 10 52 18 AM" src="https://user-images.githubusercontent.com/1813435/75183171-f08b2c00-570f-11ea-9ba3-57cb0ffa5df5.png">

**Comment by richtabor** [comment] 2020-02-24 19:50
Hey @AlchemyUnited I'm closing this issue in favor of #1377 which clearly articulates the UX adjustment to the Accordion block. Thanks for helping make CoBlocks better and better!

**Closed by richtabor** 2020-02-24 19:50 UTC
Labels: [Priority] Low, [Type] Enhancement
