### ISSUE TITLE
ISBAT duplicate a Row block without error

### ISSUE THREAD

**Issue by FellowshipAgency** [godaddy-wordpress/coblocks#308] opened 2019-02-18 10:59 UTC
**Describe the bug**
If you duplicate a row, it has the same class coblocks-row-id which means that any different settings e.g. padding, gutter, are applied to all other duplicates on the page.

**To Reproduce**
1. Create a row block and add gutter and padding "huge"
2. Add some dummy content to it
3. Duplicate it
4. Edit the duplicate, change gutter and padding to "none"
5. View the page - both blocks now have same padding and gutter

**Expected behavior**
Duplicate should get new ID so properties can be changed separately.

**WordPress theme**
Storefront

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Version: 71

**Comment by richtabor** [comment] 2019-02-20 00:08
@phpbits Remeber this is what we found earlier in testing as wel. I’m not sure what the best way to approach this would be though. :/

**Comment by EvanHerman** [comment] 2019-06-25 21:56
@richtabor Feel free to re-test this. I just tested this a number of times (with and without Gutenberg active) and was unable to reproduce the issue.

**Comment by richtabor** [comment] 2019-06-26 18:06
@EvanHerman it's when one uses the Advanced margin/padding settings - not the default/easy settings. I'm not sure how we could randomize the ID once duplicated. Ideas @jrtashjian?

![ScreenFlow](https://user-images.githubusercontent.com/1813435/60203803-740c1a80-981b-11e9-8f51-a6c3945eba52.gif)

**Comment by RubiousShaun** [comment] 2019-08-28 15:48
I definitely do not think disabling "duplicate" is the answer.

If you're fiddling around with margins and paddings, and then you want another block exactly the same, it would be a huge pain to have to recreate it identically rather than just pressing "duplicate".

There just needs to be a way to randomise the ID after it is duplicated.

**Comment by jrtashjian** [comment] 2019-08-31 03:38
After diving into #750 more, I was able make progress towards resolving this in #809. However, I had to revert much of it because each change made caused cascading issues. I still believe resolving this will be a huge undertaking as the solution changes how we implement the dimensions and responsive components shared across many of our blocks.

Randomizing the ID sounds like the most straightforward path but introduces more complexity because of how the dimensions and responsive components were architected. I need to think more about this problem to determine if there is a simpler path forward before planning a re-architecting effort.

**Comment by jrtashjian** [comment] 2019-10-22 16:12
Adding the waiting tag because we are beginning to migrate settings related to this issue into css utility classes. Example PR: https://github.com/godaddy/coblocks/pull/941

**Comment by paranoia1906** [comment] 2019-10-23 20:25
Support request on wp.org came in related to this issue.
https://wordpress.org/support/topic/reusable-coblocks-not-replicating-properly/

**Comment by jrtashjian** [comment] 2020-12-15 18:24
Closing: We are planning to deprecate the row block in the future and migrate to the `core/columns` block once we can achieve an acceptable level of feature parity.

**Closed by jrtashjian** 2020-12-15 18:24 UTC
Labels: [Priority] Low, [Status] Waiting, [Type] Bug
