### ISSUE TITLE
Stacked Gallery: Images Set to Full Width Adds a Margin to Images

### ISSUE THREAD

**Issue by katinthehatsite** [godaddy-wordpress/coblocks#1230] opened 2020-01-03 21:17 UTC
**Describe the bug**
When you set the images to the full width with the stacked gallery, they are moved outside of the box where the content is edited in the editor which creates a weird experience for customers. 
**To Reproduce**

1. Add a stacked gallery block to a page or post
<img width="697" alt="Screen Shot 2020-01-03 at 4 06 10 PM" src="https://user-images.githubusercontent.com/25575134/71749311-0df3f600-2e43-11ea-8571-a70c2081dc0d.png">

2. As the next step, add a few images to the stacked block. 

3. Set the stacked block to display images in the full width:

<img width="310" alt="Screen Shot 2020-01-03 at 4 07 23 PM" src="https://user-images.githubusercontent.com/25575134/71749380-4267b200-2e43-11ea-8632-893538b21f17.png">

**Expected behavior**
I expected the images to stay in the frame for editing them. 

The images jumped to the right in the editor:

<img width="1082" alt="Screen Shot 2020-01-03 at 4 10 26 PM" src="https://user-images.githubusercontent.com/25575134/71749481-98d4f080-2e43-11ea-9cfb-ba93266a66ab.png">

**Isolating the problem:**

This happens on WordPress.com sites - I could reproduce it with different themes activated e.g. Stow or Sketch.

**Comment by katinthehatsite** [comment] 2020-01-03 21:55
It also affects the live site and misaligns it with other content:

<img width="976" alt="Screen Shot 2020-01-03 at 4 48 52 PM" src="https://user-images.githubusercontent.com/25575134/71751515-cde44180-2e49-11ea-8f47-6afde3eae392.png">

**Comment by richtabor** [comment] 2020-01-07 19:31
@katinthehatsite, thanks for the report. Do you happen to have a URL where we could check this out in real time?

**Comment by katinthehatsite** [comment] 2020-01-07 22:43
I am seeing it in the editor of my test site: https://csstestsiteforkat.wordpress.com/2020/01/07/2900/

This is the customer's site where the margin also gets added on the site itself and not just in the editor: https://demianwohler.com/portfolio/moby-dick/

We have given them this CSS code to adjust the issue:

```
.wp-block-coblocks-gallery-stacked.alignfull .coblocks-gallery {
    margin-left: 0;
}
```

**Comment by jrtashjian** [comment] 2020-12-15 22:12
Closing. I'm unable to reproduce this issue today. This issue could be caused by the theme being used applying additional styles to certain elements.

**Closed by jrtashjian** 2020-12-15 22:12 UTC
Labels: [Priority] Low, [Type] Bug
